name: Deploy Firebase Functions

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Dependencies
        working-directory: ./functions
        run: npm ci
      
      - name: Update firebase-functions
        working-directory: ./functions
        run: npm install --save firebase-functions@latest
      
      - name: Deploy to Firebase
        run: |
          npm install -g firebase-tools
          firebase deploy --only functions --force --project narlyxdev --token "${{ secrets.FIREBASE_TOKEN }}"
